fix(piper): add the list_voices method to the Piper class
The Piper TTS test is failing because it's trying to call a `list_voices()`
method that doesn't exist in the Piper class.

The error message shows:
AttributeError: 'Piper' object has no attribute 'list_voices'

Change-Id: Ic4606f31d612a1269d47f4d8080975c13d1309ef
Signed-off-by: utsavbalar1231 <utsavbalar1231@gmail.com>